gpuid: [0]
model_type: resnet
model_name: ResNet110_cifar
force_out_dim: 0
agent_type: regularization
agent_name: EWC
optimizer: SGD
dataroot: 'data'
dataset: ['CIFAR10', 'CIFAR100']
n_permutation: 0
first_split_size: 5
other_split_size: 5
no_class_remap: False
train_aug: False
rand_split: False
rand_split_order: False
workers: 3
batch_size: 100
lr: 0.01
momentum: 0
weight_decay: 0
schedule: [2]
print_freq: 100
model_weights:
reg_coef: [0.]
eval_on_train_set: False
offline_training: False
repeat: 1
incremental_class: False